"use client";

import Link from "next/link";
import { Share2, DollarSign, Users, TrendingUp, Copy, Gift, CheckCircle2 } from "lucide-react";
import { PalmXNavbar } from "@/components/PalmXNavbar";
import { OkxFooter } from "@/components/OkxFooter";
import { useLanguage } from "@/components/LanguageProvider";

const TIERS = [
  { tier: "Starter",     referrals: "1–9",   commission: "20%", badge: "🌱", highlight: false },
  { tier: "Growth",      referrals: "10–49",  commission: "30%", badge: "🚀", highlight: false },
  { tier: "Pro",         referrals: "50–199", commission: "40%", badge: "⭐", highlight: true  },
  { tier: "Elite",       referrals: "200+",   commission: "50%", badge: "👑", highlight: false },
];

const HOW_STEPS = [
  { icon: Copy,       title: "Get Your Link",         desc: "Sign in and grab your unique referral link from the affiliate dashboard — takes 30 seconds." },
  { icon: Share2,     title: "Share Everywhere",       desc: "Post on social media, Telegram groups, YouTube, or your own blog. No minimum audience required." },
  { icon: DollarSign, title: "Earn Commission",        desc: "Receive up to 50% of trading fees from every referred user, paid daily in USDT to your wallet." },
];

const BENEFITS = [
  { icon: TrendingUp, title: "Lifetime Earnings",    desc: "Commissions last for the entire lifetime of your referred users — no expiry, ever." },
  { icon: Gift,       title: "Bonus Campaigns",       desc: "Periodic referral bonuses and competitions with extra rewards for top affiliates." },
  { icon: Users,      title: "Sub-affiliate Tier",   desc: "Earn 10% on commissions generated by affiliates you recruited. Two-tier structure." },
  { icon: CheckCircle2,title: "Real-time Dashboard", desc: "Track clicks, sign-ups, and earnings live. Withdraw anytime with zero minimum." },
];

export default function AffiliatePage() {
  const { isRTL } = useLanguage();
  const arabicFont = isRTL ? { fontFamily: "Arial, Tahoma, sans-serif" } : {};

  return (
    <div className="min-h-screen bg-black text-white flex flex-col" dir={isRTL ? "rtl" : "ltr"}>
      <PalmXNavbar />

      <main className="flex-1">
        {/* Hero */}
        <section className="pt-32 pb-20 px-6 lg:px-12 max-w-[1100px] mx-auto text-center">
          <div
            className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-wider px-3 py-1.5 rounded-full border border-[#e2b700]/30 text-[#e2b700] mb-6"
            style={arabicFont}
          >
            <Share2 className="w-3.5 h-3.5" /> Affiliate Program
          </div>
          <h1 className="text-4xl lg:text-5xl font-bold text-white leading-tight mb-5" style={arabicFont}>
            Refer Friends.<br />
            <span style={{ color: "#e2b700" }}>Earn Up to 50% Commission.</span>
          </h1>
          <p className="text-white/50 max-w-2xl mx-auto mb-10 leading-relaxed" style={arabicFont}>
            Share your referral link, help people discover PalmX, and get paid a percentage of their
            trading fees — for life. No cap. No lock-in.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link
              href="/dashboard"
              className="px-8 py-3.5 bg-[#e2b700] hover:bg-[#f5ca00] text-black font-bold rounded-xl transition-colors"
              style={arabicFont}
            >
              Join Now — It&apos;s Free
            </Link>
          </div>

          {/* Quick stats */}
          <div className="mt-16 grid grid-cols-3 gap-6 max-w-lg mx-auto">
            {[
              { val: "50%",   lbl: "Max Commission" },
              { val: "$1.2M+",lbl: "Paid to Affiliates" },
              { val: "Daily", lbl: "Payout Schedule" },
            ].map(({ val, lbl }) => (
              <div key={lbl}>
                <div className="text-2xl font-bold text-[#e2b700]">{val}</div>
                <div className="text-xs text-white/40 mt-1" style={arabicFont}>{lbl}</div>
              </div>
            ))}
          </div>
        </section>

        {/* How it works */}
        <section className="py-20 px-6 lg:px-12 bg-[#0a0a0a]">
          <div className="max-w-[1100px] mx-auto">
            <h2 className="text-2xl font-bold text-white text-center mb-12" style={arabicFont}>How It Works</h2>
            <div className="grid md:grid-cols-3 gap-6">
              {HOW_STEPS.map(({ icon: Icon, title, desc }, i) => (
                <div key={title} className="bg-[#141414] border border-white/8 rounded-2xl p-8 relative overflow-hidden">
                  <div className="absolute top-4 right-5 text-5xl font-black text-white/4 select-none">0{i + 1}</div>
                  <div className="w-12 h-12 rounded-xl bg-[#e2b700]/10 flex items-center justify-center mb-5">
                    <Icon className="w-6 h-6 text-[#e2b700]" />
                  </div>
                  <h3 className="text-base font-bold text-white mb-2" style={arabicFont}>{title}</h3>
                  <p className="text-sm text-white/50 leading-relaxed" style={arabicFont}>{desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Commission tiers */}
        <section className="py-20 px-6 lg:px-12">
          <div className="max-w-[900px] mx-auto">
            <h2 className="text-2xl font-bold text-white text-center mb-12" style={arabicFont}>Commission Tiers</h2>
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
              {TIERS.map(({ tier, referrals, commission, badge, highlight }) => (
                <div
                  key={tier}
                  className={`rounded-2xl border p-6 text-center transition-all ${
                    highlight
                      ? "border-[#e2b700] bg-[#e2b700]/5 shadow-lg shadow-[#e2b700]/10"
                      : "border-white/8 bg-[#0a0a0a]"
                  }`}
                >
                  {highlight && (
                    <div
                      className="text-[10px] font-bold uppercase tracking-wider text-[#e2b700] mb-3"
                      style={arabicFont}
                    >
                      Most Popular
                    </div>
                  )}
                  <div className="text-2xl mb-2">{badge}</div>
                  <h3 className="text-base font-bold text-white mb-1" style={arabicFont}>{tier}</h3>
                  <div className="text-xs text-white/35 mb-4" style={arabicFont}>{referrals} referrals</div>
                  <div className="text-3xl font-black text-[#e2b700]">{commission}</div>
                  <div className="text-xs text-white/35 mt-1" style={arabicFont}>of trading fees</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Benefits */}
        <section className="py-20 px-6 lg:px-12 bg-[#0a0a0a]">
          <div className="max-w-[1100px] mx-auto">
            <h2 className="text-2xl font-bold text-white text-center mb-12" style={arabicFont}>Why Become a PalmX Affiliate</h2>
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
              {BENEFITS.map(({ icon: Icon, title, desc }) => (
                <div key={title} className="bg-[#141414] border border-white/8 rounded-xl p-6">
                  <div className="w-10 h-10 rounded-xl bg-[#e2b700]/10 flex items-center justify-center mb-4">
                    <Icon className="w-5 h-5 text-[#e2b700]" />
                  </div>
                  <h3 className="text-sm font-bold text-white mb-1.5" style={arabicFont}>{title}</h3>
                  <p className="text-xs text-white/45 leading-relaxed" style={arabicFont}>{desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-24 px-6 text-center">
          <h2 className="text-3xl font-bold text-white mb-4" style={arabicFont}>Start Earning Today</h2>
          <p className="text-white/40 mb-8 max-w-md mx-auto" style={arabicFont}>
            Create your free PalmX account and access the affiliate dashboard instantly.
          </p>
          <Link
            href="/dashboard"
            className="inline-flex px-10 py-4 bg-[#e2b700] hover:bg-[#f5ca00] text-black font-bold rounded-xl transition-colors"
            style={arabicFont}
          >
            Get My Referral Link
          </Link>
        </section>
      </main>

      <OkxFooter />
    </div>
  );
}
