// Generates supabase/seed.sql from the existing static data
// (traveliun-pages.generated.json + the offer sample) so no data is lost when
// migrating into the SQL schema. Re-run after changing the static sources:
//   node scripts/generate-seed.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pages = JSON.parse(readFileSync(join(root, "src/lib/traveliun-pages.generated.json"), "utf8"));
const byRoute = Object.fromEntries(pages.map((p) => [p.route, p]));
const rows = (route) => (byRoute[route]?.rows ?? []);

// ---- value helpers ----
const s = (v) => (v === null || v === undefined || v === "" ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const num = (v) => {
  if (v === null || v === undefined || v === "") return "NULL";
  const n = Number(String(v).replace(/,/g, ""));
  return Number.isFinite(n) ? String(n) : "NULL";
};
const bool = (v) => (String(v).toLowerCase() === "yes" || v === true ? "true" : "false");
// Country lookup by the english_name used across the static data.
const countryId = (name) => (name ? `(select id from public.countries where english_name = ${s(name)} limit 1)` : "NULL");
const roleId = (name) => (name ? `(select id from public.roles where english_name = ${s(name)} limit 1)` : "NULL");

// ---- offer sample (inlined; source: src/lib/traveliun-offer-sample.ts) ----
const offer = {
  serial: "AD-1-1057-20260624",
  customer: "نايف الجهني",
  destination: "ماليزيا",
  duration: "7 ليالي - 8 أيام",
  date: "2026-06-24",
  adults: 2, children: 0, infants: 0,
  total: "7368.19", currency: "ريال سعودي", employee: "Admin",
  pdfUrl: "/offers/AD-1-1057-20260624.pdf",
  hotels: [
    { city: "كوالالمبور", hotel: "فندق سترايبس كوالالمبور أوتوجراف كوليكشن", room: "ديلوكس", checkIn: "2026-06-24", checkOut: "2026-06-29", nights: 5, meals: "شامل الإفطار", stars: 5 },
    { city: "لنكاوي", hotel: "فندق باي فيو لنكاوي", room: "غرفة سوبيريور", checkIn: "2026-06-29", checkOut: "2026-07-01", nights: 2, meals: "شامل الإفطار والغداء والعشاء", stars: 4 },
  ],
  flights: [
    { date: "2026-06-29", passengers: 2, carrier: "الخطوط الجوية العربية السعودية", from: "مطار كوالالمبور الدولي", to: "مطار لنكاوي الدولي", baggage: "20 كيلو", cabin: "7 كيلو", type: "رحلة مباشرة" },
  ],
  includes: ["الفنادق", "وجبة الإفطار", "الاستقبال والتوديع من المطار إلى الفندق والعكس", "الجولات السياحية", "الطيران الداخلي", "شريحة اتصال وباقة إنترنت", "خدمة عملاء 24 ساعة بالعربي"],
  excludes: ["وجبة الغداء والعشاء", "رسوم تذاكر دخول الأماكن السياحية"],
  terms: [
    "البرنامج قابل للتعديل حسب رغبات العميل قبل التأكيد.",
    "جميع الحجوزات تخضع لتوفر الفنادق والغرف وقت التثبيت.",
    "أسعار الفنادق والطيران قابلة للتغيير حتى اعتماد البرنامج.",
    "الجولات السياحية داخل نطاق المدينة ولا تشمل تذاكر الدخول.",
  ],
};

const out = [];
const P = (line = "") => out.push(line);

P("-- App Travluin — seed data (GENERATED by scripts/generate-seed.mjs; do not edit by hand)");
P("-- Migrates the former static data (traveliun-pages.generated.json + offer sample) into SQL.");
P("-- Run after 0001_init.sql. Safe to re-run: domain tables are truncated first.");
P("");
P("begin;");
P("");
P("truncate table");
P("  public.offer_revisions, public.pricings, public.offer_terms, public.offer_services,");
P("  public.offer_flights, public.offer_cities, public.offers, public.employees, public.roles,");
P("  public.customers, public.terms, public.flights, public.services, public.hotels,");
P("  public.room_types, public.cities, public.countries");
P("  restart identity cascade;");
P("");

// ---------- countries ----------
P("-- countries");
for (const c of rows("/countries")) {
  P(`insert into public.countries (arabic_name, english_name, default_currency, weekend) values (${s(c.arabic_name)}, ${s(c.english_name)}, ${s(c.default_currency)}, ${s(c.weekend)});`);
}
P("");

// ---------- cities ----------
P("-- cities (linked to countries by english_name)");
for (const c of rows("/cities")) {
  P(`insert into public.cities (country_id, arabic_name, english_name, default_hotel) values (${countryId(c.country)}, ${s(c.arabic_name)}, ${s(c.english_name)}, ${s(c.default_hotel)});`);
}
P("");

// ---------- room types ----------
P("-- room_types");
for (const r of rows("/rooms-types")) {
  P(`insert into public.room_types (arabic_name, english_name) values (${s(r.arabic_name)}, ${s(r.english_name)});`);
}
P("");

// ---------- roles ----------
P("-- roles");
for (const r of rows("/employees/roles")) {
  P(`insert into public.roles (arabic_name, english_name) values (${s(r.arabic_name)}, ${s(r.english_name)});`);
}
P("");

// ---------- employees ----------
// generated columns are shifted: mobile=email, email=type, type=roleName, role=status
P("-- employees (email in the source 'mobile' column; role name in 'type' column)");
for (const e of rows("/employees")) {
  P(`insert into public.employees (arabic_name, english_name, email, type, role_id, status) values (${s(e.arabic_name)}, ${s(e.english_name)}, ${s(e.mobile)}, ${s(e.email)}, ${roleId(e.type)}, ${s(e.role || "Active")});`);
}
P("");

// ---------- customers (list preserved verbatim) ----------
P("-- customers");
for (const c of rows("/customers")) {
  P(`insert into public.customers (company, arabic_name, english_name) values (${s(c.company)}, ${s(c.arabic_name)}, ${s(c.english_name)});`);
}
// ensure the offer's customer exists
P(`insert into public.customers (company, arabic_name) select 'Traveliun Travel and Tourism', ${s(offer.customer)} where not exists (select 1 from public.customers where arabic_name = ${s(offer.customer)});`);
P("");

// ---------- terms (includes / excludes / terms-and-conditions) ----------
P("-- terms catalog");
const termGroups = [
  { route: "/offers/offer-includes", kind: "include" },
  { route: "/offers/offer-not-includes", kind: "exclude" },
  { route: "/offers/terms-and-conditions", kind: "term" },
];
for (const g of termGroups) {
  rows(g.route).forEach((t, i) => {
    P(`insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('${g.kind}', ${s(t.arabic_text)}, ${s(t.english_text)}, ${bool(t.checked)}, ${i});`);
  });
}
P("");

// ---------- hotels (from the offer sample, linked to cities by arabic_name) ----------
P("-- hotels (from offer sample)");
for (const h of offer.hotels) {
  P(`insert into public.hotels (city_id, arabic_name, stars, is_default) values ((select id from public.cities where arabic_name = ${s(h.city)} limit 1), ${s(h.hotel)}, ${num(h.stars)}, false);`);
}
P("");

// ---------- offer + children ----------
P("-- sample offer with all children");
P("with new_offer as (");
P("  insert into public.offers (serial, customer_id, employee_id, destination, duration, offer_date, adults, children, infants, total, currency, status, pdf_url)");
P(`  values (${s(offer.serial)},`);
P(`    (select id from public.customers where arabic_name = ${s(offer.customer)} limit 1),`);
P(`    (select id from public.employees where english_name = ${s(offer.employee)} limit 1),`);
P(`    ${s(offer.destination)}, ${s(offer.duration)}, ${s(offer.date)}, ${offer.adults}, ${offer.children}, ${offer.infants}, ${num(offer.total)}, ${s(offer.currency)}, 'confirmed', ${s(offer.pdfUrl)})`);
P("  returning id");
P(")");
P("insert into public.offer_cities (offer_id, city_name, hotel_name, room_type, check_in, check_out, nights, meals, stars, sort)");
P("select id, v.* from new_offer, (values");
P(offer.hotels.map((h, i) => `  (${s(h.city)}, ${s(h.hotel)}, ${s(h.room)}, ${s(h.checkIn)}::date, ${s(h.checkOut)}::date, ${h.nights}, ${s(h.meals)}, ${h.stars}, ${i})`).join(",\n"));
P(") as v(city_name, hotel_name, room_type, check_in, check_out, nights, meals, stars, sort);");
P("");
P("insert into public.offer_flights (offer_id, flight_date, passengers, carrier, from_airport, to_airport, baggage, cabin, type, sort)");
P("select o.id, v.* from public.offers o, (values");
P(offer.flights.map((f, i) => `  (${s(f.date)}::date, ${f.passengers}, ${s(f.carrier)}, ${s(f.from)}, ${s(f.to)}, ${s(f.baggage)}, ${s(f.cabin)}, ${s(f.type)}, ${i})`).join(",\n"));
P(`) as v(flight_date, passengers, carrier, from_airport, to_airport, baggage, cabin, type, sort) where o.serial = ${s(offer.serial)};`);
P("");
P("insert into public.offer_services (offer_id, label, kind, sort)");
P("select o.id, v.label, v.kind::public.offer_service_kind, v.sort from public.offers o, (values");
P([
  ...offer.includes.map((l, i) => `  (${s(l)}, 'include', ${i})`),
  ...offer.excludes.map((l, i) => `  (${s(l)}, 'exclude', ${i})`),
].join(",\n"));
P(`) as v(label, kind, sort) where o.serial = ${s(offer.serial)};`);
P("");
P("insert into public.offer_terms (offer_id, text, sort)");
P("select o.id, v.text, v.sort from public.offers o, (values");
P(offer.terms.map((t, i) => `  (${s(t)}, ${i})`).join(",\n"));
P(`) as v(text, sort) where o.serial = ${s(offer.serial)};`);
P("");
P("insert into public.pricings (offer_id, total, currency)");
P(`select id, ${num(offer.total)}, ${s(offer.currency)} from public.offers where serial = ${s(offer.serial)};`);
P("");
P("insert into public.offer_revisions (offer_id, revision, note)");
P(`select id, 1, 'seed import' from public.offers where serial = ${s(offer.serial)};`);
P("");

// ---------- auth user for login (admin employee) ----------
P("-- Auth user for the Admin employee. Login: admin@admin.com / Traveliun#2026");
P("do $$");
P("declare admin_id uuid := '11111111-1111-1111-1111-111111111111';");
P("begin");
P("  if not exists (select 1 from auth.users where email = 'admin@admin.com') then");
P("    insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)");
P("    values ('00000000-0000-0000-0000-000000000000', admin_id, 'authenticated', 'authenticated', 'admin@admin.com', crypt('Traveliun#2026', gen_salt('bf')), now(), '{\"provider\":\"email\",\"providers\":[\"email\"]}', '{}', now(), now(), '', '', '', '');");
P("    insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)");
P("    values (gen_random_uuid(), admin_id, admin_id::text, jsonb_build_object('sub', admin_id::text, 'email', 'admin@admin.com'), 'email', now(), now(), now());");
P("  end if;");
P("  update public.employees set auth_user_id = (select id from auth.users where email = 'admin@admin.com') where email = 'admin@admin.com';");
P("end $$;");
P("");
P("commit;");
P("");

mkdirSync(join(root, "supabase"), { recursive: true });
writeFileSync(join(root, "supabase/seed.sql"), out.join("\n"), "utf8");
console.log("Wrote supabase/seed.sql");
