-- App Travluin — seed data (GENERATED by scripts/generate-seed.mjs; do not edit by hand)
-- Migrates the former static data (traveliun-pages.generated.json + offer sample) into SQL.
-- Run after 0001_init.sql. Safe to re-run: domain tables are truncated first.


truncate table
  public.offer_revisions, public.pricings, public.offer_terms, public.offer_services,
  public.offer_flights, public.offer_cities, public.offers, public.employees, public.roles,
  public.customers, public.terms, public.flights, public.services, public.hotels,
  public.room_types, public.cities, public.countries
  restart identity cascade;

-- countries
insert into public.countries (arabic_name, english_name, default_currency, weekend) values ('ماليزيا', 'MALASYIA', 'Ringgit Malaysia', 'Saturday, Sunday');
insert into public.countries (arabic_name, english_name, default_currency, weekend) values ('اندونيسيا', 'Indonesia', 'Indonesian rupiah', 'Sunday, Saturday');
insert into public.countries (arabic_name, english_name, default_currency, weekend) values ('فرنسا', 'Fransa', NULL, NULL);
insert into public.countries (arabic_name, english_name, default_currency, weekend) values ('تركيا', 'Turkiye', 'USD', 'Sunday, Saturday');
insert into public.countries (arabic_name, english_name, default_currency, weekend) values ('روسيا', 'russia', 'Russian ruble', 'Saturday, Sunday');
insert into public.countries (arabic_name, english_name, default_currency, weekend) values ('تايلاند', 'Thailand', 'Thai baht', 'Sunday, Saturday');
insert into public.countries (arabic_name, english_name, default_currency, weekend) values ('سويسرا', 'Switzerland', NULL, NULL);
insert into public.countries (arabic_name, english_name, default_currency, weekend) values ('السعوديه', 'Saudi Arabia', 'SAR', NULL);
insert into public.countries (arabic_name, english_name, default_currency, weekend) values ('كوريا الجنوبية', 'South Korea', NULL, NULL);
insert into public.countries (arabic_name, english_name, default_currency, weekend) values ('المغرب', 'Morocco', NULL, NULL);

-- cities (linked to countries by english_name)
insert into public.cities (country_id, arabic_name, english_name, default_hotel) values ((select id from public.countries where english_name = 'MALASYIA' limit 1), 'كوالالمبور', 'Kuala Lumpur', 'Hotel Stripes Kuala Lumpur Autograph Collection');
insert into public.cities (country_id, arabic_name, english_name, default_hotel) values ((select id from public.countries where english_name = 'Indonesia' limit 1), 'جاكرتا', 'Jakarta', 'Novotel Jakarta Cikini Hotel');
insert into public.cities (country_id, arabic_name, english_name, default_hotel) values ((select id from public.countries where english_name = 'Indonesia' limit 1), 'بالي', 'BALI', 'tanadewa villas nusa dua bali by cross collection');
insert into public.cities (country_id, arabic_name, english_name, default_hotel) values ((select id from public.countries where english_name = 'MALASYIA' limit 1), 'لنكاوي', 'Langkawi', 'Bayview Hotel Langkawi');
insert into public.cities (country_id, arabic_name, english_name, default_hotel) values ((select id from public.countries where english_name = 'MALASYIA' limit 1), 'بينانج', 'Penang', 'Hompton Hotel by the Beach');
insert into public.cities (country_id, arabic_name, english_name, default_hotel) values ((select id from public.countries where english_name = 'MALASYIA' limit 1), 'سيلانجور', 'Selangor', 'Sunway Pyramid Hotel');
insert into public.cities (country_id, arabic_name, english_name, default_hotel) values ((select id from public.countries where english_name = 'Indonesia' limit 1), 'بونشاك', 'Puncak', 'Grand ASTON Puncak Hotel and Resort');
insert into public.cities (country_id, arabic_name, english_name, default_hotel) values ((select id from public.countries where english_name = 'Indonesia' limit 1), 'باندونج', 'Bandung', 'Mercure Bandung City Centre');
insert into public.cities (country_id, arabic_name, english_name, default_hotel) values ((select id from public.countries where english_name = 'MALASYIA' limit 1), 'جنتنج هايلاند', 'Genting Highlands', NULL);
insert into public.cities (country_id, arabic_name, english_name, default_hotel) values ((select id from public.countries where english_name = 'Turkiye' limit 1), 'اسطنبول', 'Istanbul', 'Mercure Istanbul Bomonti');

-- room_types
insert into public.room_types (arabic_name, english_name) values ('جناح تيفاني', 'Tiffany Suite');
insert into public.room_types (arabic_name, english_name) values ('غرفة ديولكس مطلة على البحر', 'deluxe sea view');
insert into public.room_types (arabic_name, english_name) values ('غرفة تنفيذية', 'Executive Room');
insert into public.room_types (arabic_name, english_name) values ('غرفة وصالة', 'Suit one bedroom');
insert into public.room_types (arabic_name, english_name) values ('غرفتان وصالة', 'Suit two bedroom');
insert into public.room_types (arabic_name, english_name) values ('ثلاث غرف وصالة', 'Suit three bedrooms');
insert into public.room_types (arabic_name, english_name) values ('غرفة ضيافه ميليا', 'guest room');
insert into public.room_types (arabic_name, english_name) values ('غرفة ضيافة بريمير', 'Premier guest room');
insert into public.room_types (arabic_name, english_name) values ('عائليه من غرفتين نوم', 'Two bedroom family');
insert into public.room_types (arabic_name, english_name) values ('ديلوكس بارك', 'Deluxe Park');

-- roles
insert into public.roles (arabic_name, english_name) values ('كل الصلاحيات', 'All Permissions');
insert into public.roles (arabic_name, english_name) values ('مبيعات', 'sales');
insert into public.roles (arabic_name, english_name) values ('الاوبريشن', 'Operation');
insert into public.roles (arabic_name, english_name) values ('التأشيرات', 'Visa');

-- employees (email in the source 'mobile' column; role name in 'type' column)
insert into public.employees (arabic_name, english_name, email, type, role_id, status) values ('أدمن', 'Admin', 'admin@admin.com', 'Company Employee', (select id from public.roles where english_name = 'All Permissions' limit 1), 'Active');
insert into public.employees (arabic_name, english_name, email, type, role_id, status) values ('عبد الرزاق', 'abd alrazaq', 'abdulrazak@traveliun.com', 'Company Employee', (select id from public.roles where english_name = 'sales' limit 1), 'Active');
insert into public.employees (arabic_name, english_name, email, type, role_id, status) values ('ايمان الهاشمي', 'imenelhachmi', 'imen.elhachmi@traveliun.com', 'Company Employee', (select id from public.roles where english_name = 'All Permissions' limit 1), 'Active');
insert into public.employees (arabic_name, english_name, email, type, role_id, status) values ('احمد يوسف', 'ahmed yousif', 'sales.ksa@traveliun.com', 'Company Employee', (select id from public.roles where english_name = 'All Permissions' limit 1), 'Active');
insert into public.employees (arabic_name, english_name, email, type, role_id, status) values ('رهف', 'rahaf', 'rahaf@traveliun.com', 'Company Employee', (select id from public.roles where english_name = 'All Permissions' limit 1), 'Active');
insert into public.employees (arabic_name, english_name, email, type, role_id, status) values ('ريم', 'reem', 'visa1@traveliun.com', 'Company Employee', (select id from public.roles where english_name = 'Visa' limit 1), 'Active');
insert into public.employees (arabic_name, english_name, email, type, role_id, status) values ('محمد صالح', 'saleh', 'saleh@traveliun.com', 'Company Employee', (select id from public.roles where english_name = 'All Permissions' limit 1), 'Active');
insert into public.employees (arabic_name, english_name, email, type, role_id, status) values ('نسرين', 'visa', 'visa@traveliun.com', 'Company Employee', (select id from public.roles where english_name = 'Visa' limit 1), 'Active');
insert into public.employees (arabic_name, english_name, email, type, role_id, status) values ('هاني', 'accounts', 'accounts@traveliun.com', 'Company Employee', (select id from public.roles where english_name = 'All Permissions' limit 1), 'Active');
insert into public.employees (arabic_name, english_name, email, type, role_id, status) values ('عبدالله', 'Abdullah', 'abdallah_ali@traveliun.com', 'Company Employee', (select id from public.roles where english_name = 'All Permissions' limit 1), 'Active');

-- customers
insert into public.customers (company, arabic_name, english_name) values ('Traveliun Travel and Tourism', 'نايف الزهراني', '501040930');
insert into public.customers (company, arabic_name, english_name) values ('Traveliun Travel and Tourism', 'ابو يوسف', '560007380');
insert into public.customers (company, arabic_name, english_name) values ('Traveliun Travel and Tourism', '+966537733106', '+966537733106');
insert into public.customers (company, arabic_name, english_name) values ('Traveliun Travel and Tourism', 'الأستاذة هند', '+966544072627');
insert into public.customers (company, arabic_name, english_name) values ('Traveliun Travel and Tourism', 'رؤى الردادي', '0553300417');
insert into public.customers (company, arabic_name, english_name) values ('Traveliun Travel and Tourism', 'امجد', '+966583878771');
insert into public.customers (company, arabic_name, english_name) values ('Traveliun Travel and Tourism', 'الاستاذ بندر حسين', '0566669980');
insert into public.customers (company, arabic_name, english_name) values ('الأستاذه أم كريم', '966561003748+', NULL);
insert into public.customers (company, arabic_name, english_name) values ('Traveliun Travel and Tourism', '+966562328513', '+966562328513');
insert into public.customers (company, arabic_name, english_name) values ('Traveliun Travel and Tourism', '+966561310170', '+966561310170');
insert into public.customers (company, arabic_name) select 'Traveliun Travel and Tourism', 'نايف الجهني' where not exists (select 1 from public.customers where arabic_name = 'نايف الجهني');

-- terms catalog
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('include', 'الفنادق', 'HOTELS', true, 0);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('include', 'وجبة الإفطار', 'BREAKFAST', true, 1);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('include', 'الإستقبال والتوديع من المطار إلى الفندق والعكس', 'Reception and farewell from the airport to the hotel and vice versa', true, 2);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('include', 'الجولات السياحية', 'Tours', true, 3);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('include', 'الطيران الداخلي', 'Domestic flight', true, 4);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('include', 'الطيران الدولي', 'International flight', false, 5);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('include', 'شريحة إتصال وباقة انترنت', 'Internet and calls sim card', false, 6);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('include', 'خدمة عملاء 24 ساعة بالعربي', 'hour customer service in english 24', true, 7);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('include', 'جميع الجولات السياحية والتنقلات بسيارة خاصة بكم فقط', 'All tours and transfers by your own private car only', true, 8);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('include', 'شامل جميع الضرائب والرسوم ماعدا ضريبة المدينة إن وجدت', 'All taxes and fees included except city tax if applicable.', true, 9);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('exclude', 'الطيران الدولي', 'International flight', false, 0);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('exclude', 'وجبة الغداء والعشاء', 'Lunch and dinner', true, 1);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('exclude', 'رسوم تذاكر دخول الأماكن السياحية', 'Tourist entrance tickets', true, 2);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('term', 'في حال لم يكن حجم السيارة ملائمًا لعدد الركاب والأمتعة يُرجى إعلامنا مسبقًا نود التنويه بأن الأسعار تختلف حسب حجم السيارة', 'If the size of the car is not suitable for the number of passengers and luggage, please inform us in advance. We would like to note that prices vary according to the size of the car', true, 0);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('term', 'عبارة ( يوم حر ) المدرجة في البرنامج تعني أن الشركة غير مسؤولة عن تأمين سيارة للعميل في ذلك اليوم وأن للعميل حرية اختيار الأماكن التي يرغب في زيارتها والطريقة التي يفضلها', 'The phrase (free day) included in the program means that the company is not responsible for securing a car for the customer on that day and that the customer has the freedom to choose the places he wants to visit and the method he prefers.', true, 1);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('term', 'يُطلب من العميل التحقق من الموظف المسؤول حول توفر الفنادق في التواريخ المدرجة في البرنامج قبل تثبيت الحجز', 'The Customer is requested to check with the responsible employee about the availability of hotels on the dates listed in the program before confirming the reservation', true, 2);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('term', 'جميع الحجوزات في الفنادق غير قابلة للإلغاء أو الاسترجاع أو التعديل', 'All hotel reservations are not subject to cancellation, refund or modification', true, 3);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('term', 'السيارة الصغيرة تتسع لشخصين بالغين وحقيبتين كبيرتين', 'The small car can accommodate two adults with two large bags', true, 4);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('term', 'جميع الجولات المدرجة في البرنامج هي مقترحات قابلة للتعديل حسب رغباتكم مع التنسيق مع السائق عند الوصول بشرط أن تكون داخل نطاق المدينة', 'All tours included in the program are proposals that can be modified according to your desires, with coordination with the driver upon arrival, provided that they are within the city limits', true, 5);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('term', 'نوع السرير في الغرفة سواء كان سريرًا كبيرًا أو سريرين منفصلين يتم تحديده من قبل الفندق عند الوصول', 'The type of bed in the room, whether it is a king size bed or two separate beds, is determined by the hotel upon arrival', true, 6);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('term', 'مدة الجولة السياحية هي 8 ساعات فقط ولا تشمل تذاكر الدخول إلى الأماكن السياحية', 'The duration of the tour is only 8 hours and does not include entry tickets to tourist attractions', true, 7);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('term', 'تجنبًا للأخطاء يُرجى فحص البرنامج والغرف المذكورة في البرنامج المرسل من قبلنا قبل التأكيد', 'To avoid errors, please check the program and rooms mentioned in the program sent by us before confirming', true, 8);
insert into public.terms (kind, arabic_text, english_text, checked, sort) values ('term', 'في حال عدم توفر الغرفة أو الفندق المرسلة من قبلنا سيتم اقتراح فندق بديل يتمتع بنفس المستوى والجودة', 'If the room or hotel sent by us is not available an alternative hotel of the same level and quality will be suggested', true, 9);

-- hotels (from offer sample)
insert into public.hotels (city_id, arabic_name, stars, is_default) values ((select id from public.cities where arabic_name = 'كوالالمبور' limit 1), 'فندق سترايبس كوالالمبور أوتوجراف كوليكشن', 5, false);
insert into public.hotels (city_id, arabic_name, stars, is_default) values ((select id from public.cities where arabic_name = 'لنكاوي' limit 1), 'فندق باي فيو لنكاوي', 4, false);

-- sample offer with all children
with new_offer as (
  insert into public.offers (serial, customer_id, employee_id, destination, duration, offer_date, adults, children, infants, total, currency, status, pdf_url)
  values ('AD-1-1057-20260624',
    (select id from public.customers where arabic_name = 'نايف الجهني' limit 1),
    (select id from public.employees where english_name = 'Admin' limit 1),
    'ماليزيا', '7 ليالي - 8 أيام', '2026-06-24', 2, 0, 0, 7368.19, 'ريال سعودي', 'confirmed', '/offers/AD-1-1057-20260624.pdf')
  returning id
)
insert into public.offer_cities (offer_id, city_name, hotel_name, room_type, check_in, check_out, nights, meals, stars, sort)
select id, v.* from new_offer, (values
  ('كوالالمبور', 'فندق سترايبس كوالالمبور أوتوجراف كوليكشن', 'ديلوكس', '2026-06-24'::date, '2026-06-29'::date, 5, 'شامل الإفطار', 5, 0),
  ('لنكاوي', 'فندق باي فيو لنكاوي', 'غرفة سوبيريور', '2026-06-29'::date, '2026-07-01'::date, 2, 'شامل الإفطار والغداء والعشاء', 4, 1)
) as v(city_name, hotel_name, room_type, check_in, check_out, nights, meals, stars, sort);

insert into public.offer_flights (offer_id, flight_date, passengers, carrier, from_airport, to_airport, baggage, cabin, type, sort)
select o.id, v.* from public.offers o, (values
  ('2026-06-29'::date, 2, 'الخطوط الجوية العربية السعودية', 'مطار كوالالمبور الدولي', 'مطار لنكاوي الدولي', '20 كيلو', '7 كيلو', 'رحلة مباشرة', 0)
) as v(flight_date, passengers, carrier, from_airport, to_airport, baggage, cabin, type, sort) where o.serial = 'AD-1-1057-20260624';

insert into public.offer_services (offer_id, label, kind, sort)
select o.id, v.label, v.kind::public.offer_service_kind, v.sort from public.offers o, (values
  ('الفنادق', 'include', 0),
  ('وجبة الإفطار', 'include', 1),
  ('الاستقبال والتوديع من المطار إلى الفندق والعكس', 'include', 2),
  ('الجولات السياحية', 'include', 3),
  ('الطيران الداخلي', 'include', 4),
  ('شريحة اتصال وباقة إنترنت', 'include', 5),
  ('خدمة عملاء 24 ساعة بالعربي', 'include', 6),
  ('وجبة الغداء والعشاء', 'exclude', 0),
  ('رسوم تذاكر دخول الأماكن السياحية', 'exclude', 1)
) as v(label, kind, sort) where o.serial = 'AD-1-1057-20260624';

insert into public.offer_terms (offer_id, text, sort)
select o.id, v.text, v.sort from public.offers o, (values
  ('البرنامج قابل للتعديل حسب رغبات العميل قبل التأكيد.', 0),
  ('جميع الحجوزات تخضع لتوفر الفنادق والغرف وقت التثبيت.', 1),
  ('أسعار الفنادق والطيران قابلة للتغيير حتى اعتماد البرنامج.', 2),
  ('الجولات السياحية داخل نطاق المدينة ولا تشمل تذاكر الدخول.', 3)
) as v(text, sort) where o.serial = 'AD-1-1057-20260624';

insert into public.pricings (offer_id, total, currency)
select id, 7368.19, 'ريال سعودي' from public.offers where serial = 'AD-1-1057-20260624';

insert into public.offer_revisions (offer_id, revision, note)
select id, 1, 'seed import' from public.offers where serial = 'AD-1-1057-20260624';

-- Auth user for the Admin employee. Login: admin@admin.com / Traveliun#2026
do $$
declare admin_id uuid := '11111111-1111-1111-1111-111111111111';
begin
  if not exists (select 1 from auth.users where email = 'admin@admin.com') then
    insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
    values ('00000000-0000-0000-0000-000000000000', admin_id, 'authenticated', 'authenticated', 'admin@admin.com', crypt('Traveliun#2026', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '');
    insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
    values (gen_random_uuid(), admin_id, admin_id::text, jsonb_build_object('sub', admin_id::text, 'email', 'admin@admin.com'), 'email', now(), now(), now());
  end if;
  update public.employees set auth_user_id = (select id from auth.users where email = 'admin@admin.com') where email = 'admin@admin.com';
end $$;

